version: "3"
services:
  app:
    container_name: library-management-system
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: library-db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - libraryapp:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4:7.0
    ports:
      - "8080:80"
    volumes:
      - pgstore:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  libraryapp:
  pgstore:
